spring:
  data:
    mongodb:
      host: 10.0.1.11
      
property:
  com:
    emd:
      api:
        login:
          LoginService:
            hostPort: http://10.0.1.11:8090
        s:
          ValidationServiceImpl:
            hostPort: http://10.0.1.11:8090
        entity:
          EntityService:
            hostPort: http://10.0.1.11:8090
      db:
        hostPort: http://10.0.1.11:8090