spring:
  data:
    mongodb:
      host: 138.68.157.172
      
  rabbitmq:
    host: 138.68.157.172

eureka:
  client:
    serviceUrl:
      defaultZone: http://138.68.157.172:8762/eureka/
#EMD
property:
  com:
    emd:
      api:
        login:
          LoginService:
            hostPort: http://138.68.157.172:8090
        s:
          ValidationServiceImpl:
            hostPort: http://138.68.157.172:8090
        entity:
          EntityService:
            hostPort: http://138.68.157.172:8090

      core:
        command:
          CommandService:
            hostPort: http://138.68.157.172:8090
            gatewayHostPort: http://138.68.157.172:8091

      db:
        hostPort: http://138.68.157.172:8090