server:
  port: 8093
  
  # MONGODB
spring:
  data:
    mongodb:
      authentication-database: admin
      host: mon1.manapp.com
      port: 27017
      username: siteRootAdmin
      password: password
      # database: emd-db

property:
  com:
    emd:
      api:
        login:
          LoginService:
            hostPort: http://data.manapp.com:8090
            loggedMessage: Logged in successfully!
            expirationTime: 864000
      cors:
        origins: http://localhost:4200
        methods: POST,GET,PATCH,DELETE
      service:
        login:
          version: 190407