# MONGODB
spring:
  data:
    mongodb:
      host: 192.168.99.102
      
property:
  com:
    emd:
      data:
        hostPort: http://192.168.99.102:8090
      controler:  
        hostPort: http://192.168.99.102:8091
      host:
        hostPort: http://192.168.99.102:8090 
                                 