spring:
  application:
    name: emdBroker
    
  data:
    mongodb:
      authentication-database: admin
      host: mon1.manapp.com
      port: 27017
      username: siteRootAdmin
      password: password
      
  rabbitmq:
    addresses: mon2.manapp.com
    host: mon2.manapp.com
    
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    
server:
  port: 8081
  
#EMD
property:
  com:
    emd:
      mapper: 190425
      data:
        hostPort: http://localhost:8090
      controler:
        hostPort: http://localhost:8091
      host:
        hostPort: http://localhost:8090
