spring:
  application:
    name: emdFTPController

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  
#EMD
property:
  com:
    emd:
      db:
        hostPort: 8091
        settings:
          url: settings
      broker:
        ftpserver:
          Host: mon1.manapp.com
          Port: 21
          User: emd
          Password: jose
        ftp:
          RemoteDirectory: ./intercambio
          LocalDirectory: ./intercambio/in
          Pattern: "*"
          