spring:
  application:
    name: emdService

  data:
    mongodb:
      authentication-database: admin
      host: mon1.manapp.com
      port: 27017
      username: siteRootAdmin
      password: password

  rabbitmq:
    addresses: mon2.manapp.com
    host: mon2.manapp.com
    
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    
server:
  port: 8082

